from beanie import Document
from pydantic import Field
from datetime import datetime
from typing import Optional, List, Dict, Any

class TrendActivityModel(Document):
    """
    Model for logging trend execution history and generated prompts.
    Fulfills the "Trend Activity" audit requirement.
    """
    user_email: str = Field(..., description="The user who executed the trend")
    trend_keyword: str = Field(..., description="The original trending keyword")
    trend_source: str = Field(default="Google Trends", description="Source of the trend")
    
    # The prompt generated by RAAMP for the Content Module
    generated_prompt: str = Field(..., description="The full AI campaign prompt generated")
    
    # Metadata for the trend at time of execution
    niche: str = Field(..., description="Business niche")
    location: str = Field(..., description="Trend location")
    
    timestamp: datetime = Field(default_factory=datetime.utcnow)

    class Settings:
        name = "trend_activities"
        indexes = [
            "user_email",
            "timestamp",
            [("user_email", 1), ("timestamp", -1)]
        ]
