import React, { useState } from "react";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { HolographicCard } from "@/components/ui/holographic-card";
import { 
  Target, Users, Clock, Copy, Check, ExternalLink, 
  MapPin, Megaphone, Info, Sparkles, Zap
} from "lucide-react";
import { toast } from "sonner";
import { cn } from "@/lib/utils";

interface GeoCampaignBrief {
  campaign_id?: string;
  zone_label: string;
  dominant_persona: string;
  dominant_persona_pct: number;
  best_time_window: string;
  suggested_budget_min?: number;
  suggested_budget_max?: number;
  caption: string; // fallback
  caption_variants?: {
    aggressive: string;
    soft: string;
    urgency: string;
  };
  hashtags: string[];
  meta_objective: string;
  meta_deep_link: string;
  reasoning: string;
  heat_score: number;
  urgency: string;
  coordinates_display: string;
  timestamp?: string;
}

interface GeoCampaignBriefModalProps {
  open: boolean;
  onClose: () => void;
  brief: GeoCampaignBrief | null;
}

const GeoCampaignBriefModal: React.FC<GeoCampaignBriefModalProps> = ({ open, onClose, brief }) => {
  const [copiedField, setCopiedField] = useState<string | null>(null);
  const [selectedVariant, setSelectedVariant] = useState<'aggressive' | 'soft' | 'urgency'>('aggressive');

  const isLoading = open && !brief;

  const safeToLocaleString = (value: unknown) => {
    const n = typeof value === "number" ? value : Number(value);
    if (!Number.isFinite(n)) return "—";
    return Math.round(n).toLocaleString();
  };

  const sanitizeCreative = (text: string) =>
    String(text || "")
      // Never show dash characters in variants (per UX requirement)
      .replace(/[—–-]+/g, " ")
      .replace(/\s+/g, " ")
      .trim();

  const selectedCaption = brief
    ? sanitizeCreative(brief.caption_variants?.[selectedVariant] || brief.caption || "")
    : "";

  const copyToClipboard = async (text: string, fieldId: string) => {
    try {
      if (navigator.clipboard && navigator.clipboard.writeText) {
        await navigator.clipboard.writeText(text);
      } else {
        // Fallback for older browsers
        const textArea = document.createElement("textarea");
        textArea.value = text;
        document.body.appendChild(textArea);
        textArea.select();
        document.execCommand('copy');
        document.body.removeChild(textArea);
      }
      
      setCopiedField(fieldId);
      toast.success("Copied to clipboard");
      setTimeout(() => setCopiedField(null), 2000);
    } catch (err) {
      console.error("Failed to copy:", err);
      toast.error("Copy failed");
    }
  };

  const handleCopyFullBrief = () => {
    if (!brief) return;
    const fullText = `
RAAMP GEO-TARGETED CAMPAIGN BRIEF
===================================
Zone: ${brief.zone_label}
Coordinates: ${brief.coordinates_display}
Heat Score: ${brief.heat_score}/100 (${brief.urgency})

PRIMARY AUDIENCE
${brief.dominant_persona} — ${brief.dominant_persona_pct}%

BEST TIME TO RUN
${brief.best_time_window}

SUGGESTED BUDGET
PKR ${safeToLocaleString(brief.suggested_budget_min)} to PKR ${safeToLocaleString(brief.suggested_budget_max)} / day

CAMPAIGN OBJECTIVE: ${brief.meta_objective}

CAPTION
${sanitizeCreative(brief.caption)}

HASHTAGS
${brief.hashtags.map(h => '#' + h.replace(/^#/, '')).join(' ')}

WHY THIS ZONE
${brief.reasoning}

Generated by RAAMP Geo-Intent Engine
    `.trim();
    
    copyToClipboard(fullText, 'full');
  };

  const urgencyColors: Record<string, string> = {
    "Low": "bg-green-500/20 text-green-400 border-green-500/30",
    "Medium": "bg-yellow-500/20 text-yellow-400 border-yellow-500/30",
    "High": "bg-orange-500/20 text-orange-400 border-orange-500/30",
    "Critical": "bg-red-500/20 text-red-500 border-red-500/30",
  };

  return (
    <Dialog open={open} onOpenChange={onClose}>
      <DialogContent className="max-w-4xl max-h-[90vh] bg-background/95 backdrop-blur-xl border-primary/20 p-0 overflow-hidden">
        {/* Header Decor */}
        <div className="absolute top-0 inset-x-0 h-1 bg-gradient-to-r from-transparent via-primary to-transparent opacity-50" />
        
        <div className="p-8 space-y-8 max-h-[90vh] overflow-y-auto">
          <DialogHeader>
            <div className="flex items-center justify-between gap-4 flex-wrap">
              <div className="space-y-1">
                <div className="flex items-center gap-3">
                  <DialogTitle className="text-2xl font-bold font-heading text-foreground tracking-tight">
                    Geo-Targeted Campaign Brief
                  </DialogTitle>
                  {brief && (
                    <Badge
                      variant="outline"
                      className={cn(
                        "font-mono text-[10px] py-0 h-5 px-2",
                        urgencyColors[brief.urgency] || urgencyColors.Low
                      )}
                    >
                      {String(brief.urgency || "Low").toUpperCase()} INTENT
                    </Badge>
                  )}
                </div>
                <DialogDescription className="font-mono text-xs text-muted-foreground uppercase tracking-widest flex items-center gap-2">
                  <MapPin className="w-3 h-3 text-primary" />
                  {brief?.zone_label || "Generating brief…"}
                </DialogDescription>
              </div>
              <div className="bg-primary/10 border border-primary/20 rounded-lg px-4 py-2 flex items-center gap-3">
                <div className="text-right">
                  <p className="text-[10px] font-mono text-muted-foreground uppercase leading-none mb-1">Target Coordinates</p>
                  <p className="text-xs font-mono font-bold text-primary">{brief?.coordinates_display || "—"}</p>
                </div>
                <div className="w-px h-8 bg-primary/20" />
                <Zap className="w-5 h-5 text-primary animate-pulse" />
              </div>
            </div>
          </DialogHeader>

          {isLoading ? (
            <div className="py-16 flex items-center justify-center">
              <div className="flex items-center gap-3 text-sm font-mono text-muted-foreground">
                <div className="h-5 w-5 rounded-full border-2 border-primary border-t-transparent animate-spin" />
                Generating strategy brief…
              </div>
            </div>
          ) : !brief ? null : (
          {/* ROW 1: Intelligence Stats */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            <StatCard 
              icon={<Sparkles className="w-4 h-4 text-primary" />} 
              label="Heat Score" 
              value={`${brief.heat_score}/100`} 
              subValue="Real-time Receptivity"
            />
            <StatCard 
              icon={<Users className="w-4 h-4 text-primary" />} 
              label="Primary Audience" 
              value={brief.dominant_persona}
              subValue={`${brief.dominant_persona_pct}% concentration`}
            />
            <StatCard 
              icon={<Clock className="w-4 h-4 text-primary" />} 
              label="Best Window" 
              value={String(brief.best_time_window || "").split('—')[0].trim() || "—"}
              subValue={String(brief.best_time_window || "").split('—')[1]?.trim() || "Optimal Window"}
            />
          </div>

          {/* ROW 2: Campaign Details */}
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
            {/* Left Box: Creative */}
            <div className="space-y-6">
              <div className="space-y-3">
                <div className="flex justify-between items-center">
                  <label className="text-[10px] font-mono text-muted-foreground uppercase tracking-wider flex items-center gap-2">
                    <Megaphone className="w-3 h-3 text-primary" />
                    AI Creative Variants
                  </label>
                  <div className="flex gap-1">
                    {(['aggressive', 'soft', 'urgency'] as const).map((v) => (
                      <button
                        key={v}
                        onClick={() => setSelectedVariant(v)}
                        className={cn(
                          "px-2 py-0.5 rounded text-[9px] font-mono border transition-all",
                          selectedVariant === v 
                            ? "bg-primary text-black border-primary font-bold" 
                            : "bg-transparent text-muted-foreground border-border hover:border-primary/50"
                        )}
                      >
                        {v.toUpperCase()}
                      </button>
                    ))}
                  </div>
                </div>
                <div className="relative group">
                  <div className="bg-primary/5 border border-primary/20 rounded-xl p-5 text-sm leading-relaxed italic text-foreground min-h-[120px] flex items-center shadow-inner">
                    "{selectedCaption}"
                  </div>
                  <button 
                    onClick={() => copyToClipboard(selectedCaption, 'caption')}
                    className="absolute bottom-3 right-3 p-1.5 bg-background/50 backdrop-blur border border-border rounded-lg text-primary opacity-0 group-hover:opacity-100 transition-opacity"
                  >
                    {copiedField === 'caption' ? <Check className="w-3 h-3" /> : <Copy className="w-3 h-3" />}
                  </button>
                </div>
              </div>

              <div className="space-y-3">
                <div className="flex justify-between items-center">
                  <label className="text-[10px] font-mono text-muted-foreground uppercase tracking-wider flex items-center gap-2">
                    <Target className="w-3 h-3 text-primary" />
                    Suggested Hashtags
                  </label>
                  <button 
                    onClick={() => copyToClipboard(brief.hashtags.map(h => '#' + h.replace(/^#/, '')).join(' '), 'hashtags')}
                    className="text-[10px] font-mono text-primary flex items-center gap-1 hover:underline"
                  >
                    {copiedField === 'hashtags' ? <Check className="w-3 h-3" /> : <Copy className="w-3 h-3" />}
                    {copiedField === 'hashtags' ? 'COPIED' : 'COPY ALL'}
                  </button>
                </div>
                <div className="flex flex-wrap gap-2">
                  {brief.hashtags.map((tag, idx) => (
                    <Badge key={idx} variant="secondary" className="bg-foreground/5 hover:bg-foreground/10 border-border font-mono text-[10px] py-0.5">
                      #{tag.replace(/^#/, '')}
                    </Badge>
                  ))}
                </div>
              </div>
            </div>

            {/* Right Box: Logistics */}
            <div className="bg-foreground/5 border border-border/50 rounded-2xl p-6 space-y-6">
              <div className="grid grid-cols-2 gap-4">
                <div className="space-y-1">
                  <p className="text-[9px] font-mono text-muted-foreground uppercase">Suggested Budget</p>
                  <p className="text-sm font-bold text-foreground">
                    PKR {brief.suggested_budget_min.toLocaleString()} – {brief.suggested_budget_max.toLocaleString()}
                    <span className="text-[10px] font-normal text-muted-foreground ml-1">/ day</span>
                  </p>
                </div>
                <div className="space-y-1">
                  <p className="text-[9px] font-mono text-muted-foreground uppercase">Campaign Objective</p>
                  <Badge variant="outline" className="bg-primary/5 text-primary border-primary/40 font-mono text-[10px]">
                    {brief.meta_objective}
                  </Badge>
                </div>
              </div>

              <div className="space-y-1">
                <p className="text-[9px] font-mono text-muted-foreground uppercase">Targeting Placement</p>
                <div className="flex items-center gap-2">
                  <Badge variant="secondary" className="bg-background border border-border text-[9px]">INSTAGRAM FEED</Badge>
                  <Badge variant="secondary" className="bg-background border border-border text-[9px]">INSTAGRAM EXPLORE</Badge>
                </div>
              </div>

              <div className="pt-4 border-t border-border/50">
                <p className="text-[10px] font-mono text-muted-foreground uppercase flex items-center gap-2 mb-3">
                   <Info className="w-3 h-3 text-primary" />
                   AI Strategy Recommendation
                </p>
                <p className="text-xs text-muted-foreground italic leading-relaxed">
                  "Based on the high {brief.dominant_persona} activity and current {brief.urgency.toLowerCase()} urgency, 
                  we recommend the {brief.meta_objective} objective to maximize local footprint within this {brief.zone_label}."
                </p>
              </div>
            </div>
          </div>

          {/* ROW 3: Reasoning */}
          <div className="bg-primary/5 border border-primary/10 rounded-2xl p-5">
            <h4 className="text-[10px] font-mono text-primary uppercase font-bold mb-2 flex items-center gap-2">
               <Zap className="w-3 h-3" />
               WHY THIS ZONE?
            </h4>
            <p className="text-xs text-muted-foreground italic leading-relaxed">
               {brief.reasoning}
            </p>
          </div>

          {/* Footer Buttons */}
          <div className="flex flex-col sm:flex-row gap-3 pt-4 items-center justify-between">
            <div className="flex gap-2">
              <Button 
                  variant="outline" 
                  size="sm"
                  onClick={handleCopyFullBrief}
                  className="font-mono text-[10px] gap-2 border-primary/20 hover:bg-primary/5 h-10"
              >
                {copiedField === 'full' ? <Check className="w-3 h-3" /> : <Copy className="w-3 h-3" />}
                {copiedField === 'full' ? 'BRIEF COPIED' : 'COPY FULL BRIEF'}
              </Button>
              {brief.campaign_id && (
                <div className="hidden sm:flex items-center gap-2 px-3 border border-border rounded-md bg-muted/30">
                  <Check className="w-3 h-3 text-primary" />
                  <span className="text-[9px] font-mono text-muted-foreground">ID: {brief.campaign_id.substring(0, 8)}...</span>
                </div>
              )}
            </div>
            
            <Button 
                asChild
                className="w-full sm:w-auto px-10 bg-primary text-black font-bold hover:bg-primary/90 h-11 gap-2 shadow-[0_0_20px_rgba(0,224,208,0.3)] shadow-primary/20"
            >
              <a href={brief.meta_deep_link} target="_blank" rel="noopener noreferrer">
                OPEN META ADS MANAGER
                <ExternalLink className="w-4 h-4" />
              </a>
            </Button>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
};

interface StatCardProps {
  icon: React.ReactNode;
  label: string;
  value: string;
  subValue: string;
}

const StatCard: React.FC<StatCardProps> = ({ icon, label, value, subValue }) => (
  <HolographicCard className="p-4 border-primary/10 hover:border-primary/30 transition-all group">
    <div className="flex flex-col gap-1">
      <div className="flex justify-between items-start">
        <span className="text-[9px] font-mono text-muted-foreground uppercase">{label}</span>
        {icon}
      </div>
      <p className="text-lg font-bold font-heading text-foreground group-hover:text-primary transition-colors">{value}</p>
      <p className="text-[9px] font-mono text-muted-foreground/60">{subValue}</p>
    </div>
  </HolographicCard>
);

export default GeoCampaignBriefModal;
